### ISSUE TITLE
Support for pip 10.0.0

### ISSUE THREAD

**Issue by albydeca** [kimdhamilton/merkle-proofs#1]
This dependency currently triggers an error when an attempt is made to install it via the newest pip, 10.0.0. The error in question is the following:
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cb/gkv75y0s46xd_k84rktfppw80000gn/T/pip-install-7fXXv5/merkle-proofs/setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
```
Whilst it works fine on 9.x.x, suggesting pip 10 has changed module structure

**Comment by albydeca** [comment]
stale. Closing
